# Generated by Django 5.1.6 on 2025-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cierre_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
